# Generated by Django 3.2.2 on 2021-05-27 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shortener', '0003_alter_shortenedurl_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('update', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sh_url', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='shortener.shortenedurl')),
            ],
        ),
    ]
