# Generated by Django 3.2.2 on 2021-05-26 19:12

from django.db import migrations, models
import shortener.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20210513_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='url',
            field=models.CharField(max_length=200, validators=[shortener.validators.validate_url, shortener.validators.validate_dot_com]),
        ),
    ]
